version: "3.9"

services:
  gradio_app:
    build: .
    container_name: gradio_app
    restart: unless-stopped
    ports:
      - "7860:7860"
    environment:
      - llm.groq.apiKey=${API_KEY}
    volumes:
      - ./data:/app/data
    command: >
      sh -c "python src/app.py"
